# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="snackkster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

#ALIAS SECTION

alias ls='ls -l --color'

#SSH CONNECTIONS
alias owncloud='ssh -p 1337 pi@owncloud.flnet.org'
alias mark1='ssh -p 1337 pi@mark1.darktech.org'
alias owncloud_temp='ssh -p 1337 pi@owncloud.flnet.org "/opt/vc/bin/vcgencmd measure_temp"'
alias mark1_temp='ssh -p 1337 pi@mark1.darktech.org "/opt/vc/bin/vcgencmd measure_temp"'
alias sigma='ssh ist173972@sigma.ist.utl.pt'
alias generate_assymetric_keys='ssh-keygen -t rsa'


#PACMAN
alias pacman_orphans='pacman -Qdt'
alias pacman_installed='pacman -Qen'
alias aur_installed='pacman -Qem'
alias pacman_remove_orphans='sudo pacman -Rns $(pacman -Qtdq)'
alias pacman_new='find / -regextype posix-extended -regex ".+\.pac(new|save|orig)" 2> /dev/null'

#GITHUB
alias git_setup_name='git config --global user.name "snackk"'
alias git_setup_email='git config --global user.email "santos_matrix@sapo.pt"'
alias git_setup_timeout='git config --global credential.helper 'cache --timeout=3600''
alias git_list='git config --list'

#UTILS
alias generate_lostFiles='lostfiles > ~/Downloads/LostFiles.txt'
alias checkProblems='journalctl -p 0..3 -xn'
alias flushdns='sudo nscd -K && nscd'
alias wired='sudo iplink set enp8s0 up && sudo dhcpd enp8s0'
alias cleanHistory='rm $HISTFILE'

alsi --color1=blue --color2=black -a
